# Generated by Django 4.1.2 on 2022-10-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('family', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(max_length=9, verbose_name='کد ملی')),
                ('birth_certificate_number', models.IntegerField(max_length=9, verbose_name='شماره شناسنامه')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('address', models.TextField(max_length=250, verbose_name='آدرس')),
                ('doz1', models.BooleanField(default=True, verbose_name='دوز اول')),
                ('doz2', models.BooleanField(default=False, verbose_name='دوز دوم')),
                ('doz3', models.BooleanField(default=False, verbose_name='دوز سوم')),
                ('doz4', models.BooleanField(default=False, verbose_name='دوز چهارم')),
                ('doz1_time', models.DateField(auto_now_add=True, verbose_name='تاری خ دریافت دوز اول')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='vaccine.vaccine', verbose_name='نام واکسن تزریق شده')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیمار ها',
                'ordering': ['name', 'family'],
            },
        ),
    ]
