# Generated by Django 4.1.2 on 2022-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_certificate_number',
            field=models.CharField(max_length=9, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(max_length=9, verbose_name='کد ملی'),
        ),
    ]
