# Generated by Django 4.1.2 on 2022-10-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_vaccine_availablity_vaccine_description_and_more'),
        ('patient', '0004_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccines', to='vaccine.vaccine', verbose_name='نام واکسن تزریق شده'),
        ),
    ]
