# Generated by Django 4.1.2 on 2022-10-16 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doz1_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاری خ دریافت دوز اول'),
        ),
    ]
