# Generated by Django 4.1.2 on 2022-10-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_vaccine_availablity_vaccine_description_and_more'),
        ('patient', '0007_alter_patient_birth_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doz2_time',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت دوز دوم'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doz3_time',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت دوز سوم'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doz4_time',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت دوز چهارم'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccine2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine2', to='vaccine.vaccine', verbose_name='نام واکسن دوز دوم'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccine3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine3', to='vaccine.vaccine', verbose_name='نام واکسن دوز سوم'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccine4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccine4', to='vaccine.vaccine', verbose_name='نام واکسن دوز چهارم'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine1', to='vaccine.vaccine', verbose_name='نام واکسن دوز اول'),
        ),
    ]
