# Generated by Django 4.1.2 on 2022-10-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_alter_category_status'),
        ('patient', '0011_alter_patient_vaccine_alter_patient_vaccine2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vaccine3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine3', to='vaccine.vaccine', verbose_name='نام واکسن دوز سوم'),
        ),
    ]
