# Generated by Django 4.1.2 on 2022-11-02 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patient_vaccine3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doz2_time',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 2, 19, 21, 6, 165886), null=True, verbose_name='تاریخ دریافت دوز دوم'),
        ),
    ]
