# Generated by Django 4.1.2 on 2022-11-02 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_patient_doz2_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doz2_time',
            field=models.DateField(default=datetime.timedelta(days=30), verbose_name='تاریخ دریافت دوز دوم'),
        ),
    ]
