# Generated by Django 4.1.2 on 2022-11-02 16:18

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_patient_doz2_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doz2_time',
            field=models.DateField(default=patient.models.get_doz2_time, verbose_name='تاریخ دریافت دوز دوم'),
        ),
    ]
