# Generated by Django 4.1.2 on 2022-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام واکسن')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نشانی واکسن')),
                ('country', models.CharField(max_length=100, verbose_name='کشور تولید کننده')),
                ('count', models.CharField(max_length=10, verbose_name='تعداد دوز های وارد شده به کشور')),
            ],
            options={
                'verbose_name': 'واکسن',
                'verbose_name_plural': 'واکسن ها',
                'ordering': ['count', 'name'],
            },
        ),
    ]
