# Generated by Django 4.1.2 on 2022-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='availablity',
            field=models.BooleanField(default=True, verbose_name='وضعیت موجودی واکسن'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات واکسن'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='picture',
            field=models.ImageField(default='images/vaccine_def.jpg', upload_to='images', verbose_name='تصویر واکسن'),
        ),
    ]
