# Generated by Django 4.1.2 on 2022-10-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_vaccine_availablity_vaccine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='count',
            field=models.CharField(max_length=10, verbose_name='تعداد دوز های موجود'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته یندی')),
                ('status', models.BooleanField(verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن دسته بندی')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vaccine.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='vaccine',
            name='category',
            field=models.ManyToManyField(related_name='vaccines', to='vaccine.category', verbose_name='دسته بندی'),
        ),
    ]
