# Generated by Django 4.1.2 on 2022-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='count',
            field=models.IntegerField(verbose_name='تعداد دوز های موجود'),
        ),
    ]
