# Generated by Django 4.1.2 on 2022-11-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0005_alter_vaccine_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='usage',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد دوز های موجود '),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='count',
            field=models.IntegerField(verbose_name='تعداد دوز های وارد شده'),
        ),
    ]
