# Generated by Django 4.1.2 on 2022-10-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='profile_Avatar',
            new_name='profile_avatar',
        ),
    ]
